Repository WRITE-ROOM/SERVER, pull requests merged in 2024-02, with the labels that each got.

#42 [FEAT] Error Response 형식 수정
  src/main/java/com/main/writeRoom/apiPayload/ApiResponse.java
  src/main/java/com/main/writeRoom/controller/BookmarkController.java
  src/main/java/com/main/writeRoom/controller/SearchController.java
Labels: ✨ FEAT, ♻️ REFACTOR

#43 [FEAT] 룸 정보 조회 시 커버 이미지 조회 포함 #41
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomResponseDTO.java
Labels: ✨ FEAT

#48 [FEAT] 나의 챌린지 관련 API 구현
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/ChallengeController.java
  src/main/java/com/main/writeRoom/controller/ChallengeRestController.java
  src/main/java/com/main/writeRoom/converter/ChallengeConverter.java
  src/main/java/com/main/writeRoom/domain/Challenge/ChallengeGoals.java
  src/main/java/com/main/writeRoom/domain/Challenge/ChallengeRoutine.java
  src/main/java/com/main/writeRoom/domain/mapping/ChallengeGoalsParticipation.java
  src/main/java/com/main/writeRoom/domain/mapping/ChallengeRoutineParticipation.java
  src/main/java/com/main/writeRoom/domain/mapping/ChallengeStatus.java
  src/main/java/com/main/writeRoom/domain/mapping/IsActive.java
  src/main/java/com/main/writeRoom/repository/ChallengeGoalsParticipationRepository.java
  src/main/java/com/main/writeRoom/repository/ChallengeRoutineParticipationRepository.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/MyChallengeCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/MyChallengeCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/MyChallengeQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/MyChallengeQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/challenge/ChallengeResponseDTO.java
Labels: ✨ FEAT

#51 [FEAT] 이메일 로그인, 회원가입 구현 #46
  build.gradle
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/config/PasswordEncoderConfig.java
  src/main/java/com/main/writeRoom/config/SecurityConfig.java
  src/main/java/com/main/writeRoom/config/WebConfig.java
  src/main/java/com/main/writeRoom/config/auth/AuthUser.java
  src/main/java/com/main/writeRoom/config/auth/AuthenticationArgumentResolver.java
  src/main/java/com/main/writeRoom/config/filter/JwtAuthFilter.java
  src/main/java/com/main/writeRoom/config/utils/JwtUtil.java
  src/main/java/com/main/writeRoom/controller/AuthController.java
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/UserConverter.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/domain/enums/Role.java
  src/main/java/com/main/writeRoom/handler/CustomAccessDeniedHandler.java
  src/main/java/com/main/writeRoom/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/main/writeRoom/repository/UserRepository.java
  src/main/java/com/main/writeRoom/service/AuthService/AuthService.java
  src/main/java/com/main/writeRoom/service/AuthService/AuthServiceImpl.java
  src/main/java/com/main/writeRoom/service/UserService/CustomUserDetails.java
  src/main/java/com/main/writeRoom/service/UserService/CustomUserDetailsService.java
  src/main/java/com/main/writeRoom/web/dto/user/UserRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/user/UserResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#52 [CHORE] 서버 배포 시 /health auth 허용 추가 #46
  src/main/java/com/main/writeRoom/config/SecurityConfig.java
  src/main/java/com/main/writeRoom/config/utils/JwtUtil.java
  src/main/resources/application.yml
Labels: 🔒CHORE

#54 [REFACTOR] 카테고리 목록 조회 API 수정 [FIX] 룸 삭제 시 노트 태그 리스트도 삭제 #53
  src/main/java/com/main/writeRoom/converter/CategoryConverter.java
  src/main/java/com/main/writeRoom/domain/Note.java
  src/main/java/com/main/writeRoom/domain/Room.java
  src/main/java/com/main/writeRoom/domain/Tag.java
  src/main/java/com/main/writeRoom/web/dto/category/CategoryResponseDTO.java
Labels: ♻️ REFACTOR, ⚒️ FIX

#57 [REFACTOR] 챌린지 컨트롤러 userId를 @AuthUser로 변경 #56
  src/main/java/com/main/writeRoom/controller/ChallengeController.java
Labels: ♻️ REFACTOR

#58 [FIX] 타입 Long을 long으로 수정 #56
  src/main/java/com/main/writeRoom/controller/ChallengeController.java
Labels: ⚒️ FIX

#59 [REFACTOR] @PathVariable userId 전부 @AuthUser로 변경 #55
  src/main/java/com/main/writeRoom/controller/NoteController.java
  src/main/java/com/main/writeRoom/controller/RoomController.java
Labels: ♻️ REFACTOR

#61 [FIX] 룸 도메인 기능 수정 #60
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomRequestDTO.java
Labels: ⚒️ FIX

#62 [FIX] 룸 생성 이미지 지정 방식 수정 #60
  src/main/java/com/main/writeRoom/controller/RoomController.java
Labels: ⚒️ FIX

#64 [BUILD] 클라이언트 요청 시 파일 최대 크기 제한 수정
  .platform/nginx.conf
Labels: ⚒️ FIX

#77 [REFACTOR] 룸 조회시 페이징 처리 listSize 변경 #76
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
Labels: ♻️ REFACTOR

#78 [FIX] 룸 도메인 페이징 응답 추가
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/room/roomPaticipation/userRoomResponseDTO.java
Labels: ⚒️ FIX

#80 [FIX] 사진 저장 시 s3 내 폴더 구분 #76
  src/main/java/com/main/writeRoom/aws/s3/AmazonS3Manager.java
  src/main/java/com/main/writeRoom/config/AmazonConfig.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
  src/main/resources/application.yml
Labels: ⚒️ FIX

#87 [FIX] JWT 토큰, SpringSecurity 이전으로 변경
  src/main/java/com/main/writeRoom/config/SecurityConfig.java
  src/main/java/com/main/writeRoom/controller/UserController.java
  src/main/java/com/main/writeRoom/converter/UserConverter.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/oauth/config/JwtFilter.java
  src/main/java/com/main/writeRoom/oauth/config/SecurityConfig.java
  src/main/java/com/main/writeRoom/service/UserService/UserCommandService.java
  src/main/java/com/main/writeRoom/service/UserService/UserCommandServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/user/UserRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/user/UserResponseDTO.java
Labels: ⚒️ FIX

#88 [REFACTOR] security 접근 url 수정 #81
  src/main/java/com/main/writeRoom/config/SecurityConfig.java
Labels: ♻️ REFACTOR

#89 [FIX] accessToken 인증 수정 #81
  src/main/java/com/main/writeRoom/oauth/OAuthLoginService.java
  src/main/java/com/main/writeRoom/oauth/domain/AuthTokensGenerator.java
Labels: ⚒️ FIX

#90 [FEAT] 챌린지 성공, 실패 구현
  src/main/java/com/main/writeRoom/WriteRoomApplication.java
  src/main/java/com/main/writeRoom/controller/NoteController.java
  src/main/java/com/main/writeRoom/domain/mapping/ChallengeGoalsParticipation.java
  src/main/java/com/main/writeRoom/domain/mapping/ChallengeRoutineParticipation.java
  src/main/java/com/main/writeRoom/repository/ChallengeGoalsParticipationRepository.java
  src/main/java/com/main/writeRoom/repository/ChallengeRoutineParticipationRepository.java
  src/main/java/com/main/writeRoom/scheduler/ChallengeScheduler.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
Labels: ✨ FEAT

#92 [FEAT] 마이프로필 유저 관리 기능 추가 #81
  src/main/java/com/main/writeRoom/controller/UserController.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/oauth/OAuthLoginService.java
  src/main/java/com/main/writeRoom/repository/UserRepository.java
  src/main/java/com/main/writeRoom/service/AuthService/AuthServiceImpl.java
  src/main/java/com/main/writeRoom/service/UserService/UserCommandService.java
  src/main/java/com/main/writeRoom/service/UserService/UserCommandServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/user/UserRequestDTO.java
Labels: ✨ FEAT

#98 [FEAT] 비밀번호 변경 API #81
  build.gradle
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/AuthController.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/handler/TokenHandler.java
  src/main/java/com/main/writeRoom/repository/UserRepository.java
  src/main/java/com/main/writeRoom/service/AuthService/AuthService.java
  src/main/java/com/main/writeRoom/service/AuthService/AuthServiceImpl.java
  src/main/java/com/main/writeRoom/service/MailService/EmailService.java
  src/main/java/com/main/writeRoom/service/UserService/UserQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/user/UserRequestDTO.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#99 [FEAT] 룸에서 챌린지 달성률 조회 추가 #50
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomResponseDTO.java
Labels: ✨ FEAT

#100 [FIX] 룸에 이미 참여시 예외처리 추가 #60
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/handler/RoomParticipationHandler.java
  src/main/java/com/main/writeRoom/repository/RoomParticipationRepository.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
Labels: ⚒️ FIX

#102 [FEAT] 태그 검색 API #101
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/converter/TagConverter.java
  src/main/java/com/main/writeRoom/repository/NoteTagRepository.java
  src/main/java/com/main/writeRoom/repository/TagRepository.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/TagService/TagQueryService.java
  src/main/java/com/main/writeRoom/service/TagService/TagQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/tag/TagResponseDTO.java
Labels: ✨ FEAT

#107 [FEAT] 챌린지 관련 기능 구현 및 수정
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/ChallengeController.java
  src/main/java/com/main/writeRoom/converter/ChallengeConverter.java
  src/main/java/com/main/writeRoom/repository/RoomParticipationRepository.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/RoomParticipationService/RoomParticipationService.java
  src/main/java/com/main/writeRoom/service/RoomParticipationService/RoomParticipationServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/challenge/ChallengeResponseDTO.java
Labels: ✨ FEAT

#108 [FEAT] 비밀번호 재설정 API 구현 #101
  src/main/java/com/main/writeRoom/controller/AuthController.java
  src/main/java/com/main/writeRoom/controller/UserController.java
  src/main/java/com/main/writeRoom/converter/UserConverter.java
  src/main/java/com/main/writeRoom/domain/User/ExistedEmail.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/repository/ExistedEmailRespository.java
  src/main/java/com/main/writeRoom/service/AuthService/AuthService.java
  src/main/java/com/main/writeRoom/service/AuthService/AuthServiceImpl.java
  src/main/java/com/main/writeRoom/service/MailService/EmailService.java
  src/main/java/com/main/writeRoom/service/UserService/UserCommandService.java
  src/main/java/com/main/writeRoom/service/UserService/UserCommandServiceImpl.java
Labels: ✨ FEAT, ♻️ REFACTOR

#109 [REFACTOR] 이메일 인증 메일 ui 수정 #101
  src/main/java/com/main/writeRoom/service/MailService/EmailService.java
Labels: ♻️ REFACTOR

#114 [FIX] 룸 생성시 카테고리 빠른노트 자동 추가 #113
  src/main/java/com/main/writeRoom/converter/CategoryConverter.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
Labels: ⚒️ FIX

#115 [REFACTER] 기존에 맡아서 작성한 API 리팩터링 #112
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/BookmarkController.java
  src/main/java/com/main/writeRoom/controller/EmojiController.java
  src/main/java/com/main/writeRoom/controller/NoteController.java
  src/main/java/com/main/writeRoom/controller/SearchController.java
  src/main/java/com/main/writeRoom/converter/BookmarkConverter.java
  src/main/java/com/main/writeRoom/converter/EmojiConverter.java
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/domain/Bookmark/BookmarkMaterial.java
  src/main/java/com/main/writeRoom/domain/Emoji.java
  src/main/java/com/main/writeRoom/domain/Note.java
  src/main/java/com/main/writeRoom/domain/Tag.java
  src/main/java/com/main/writeRoom/handler/AuthenticityHandler.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkQueryService.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkService.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkServiceImpl.java
  src/main/java/com/main/writeRoom/service/EmojiService/EmojiCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/EmojiService/EmojiQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/bookmark/BookmarkRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/bookmark/BookmarkResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/emoji/EmojiResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/search/SearchRequestDTO.java
Labels: ♻️ REFACTOR

#119 [REFACTOR] GPT 사용 API 응답 형태 통일 #116
  src/main/java/com/main/writeRoom/service/SearchService/SearchQueryService.java
  src/main/java/com/main/writeRoom/service/SearchService/SearchQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/search/SearchResponseDTO.java
Labels: ♻️ REFACTOR

#121 [FIX] 나의 룸 목록 조회시 페이징 기능 수정 #118
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandService.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomResponseDTO.java
Labels: ⚒️ FIX

#122 [FEAT] 로그아웃 기능 추가 #103
  src/main/java/com/main/writeRoom/controller/AuthController.java
Labels: ✨ FEAT

#124 [FEAT] 노트 북마크 리스트 조회 #123
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/NoteController.java
  src/main/java/com/main/writeRoom/converter/BookmarkConverter.java
  src/main/java/com/main/writeRoom/repository/BookmarkNoteRepository.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkService.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/bookmark/BookmarkResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
Labels: ✨ FEAT, ♻️ REFACTOR

#125 [REFACTOR] 북마크 조회 시 유저 이미지 추가 #123
  src/main/java/com/main/writeRoom/converter/BookmarkConverter.java
  src/main/java/com/main/writeRoom/web/dto/bookmark/BookmarkResponseDTO.java
Labels: ♻️ REFACTOR

#127 [REFACTOR] 챌린지 주석 처리된 코드 삭제 #126
  src/main/java/com/main/writeRoom/scheduler/ChallengeScheduler.java
Labels: ♻️ REFACTOR

#128 [REFACTOR] 북마크한 노트 조회시 응답 데이터 추가 #123
  src/main/java/com/main/writeRoom/converter/BookmarkConverter.java
  src/main/java/com/main/writeRoom/web/dto/bookmark/BookmarkResponseDTO.java
Labels: ♻️ REFACTOR

#129 [BUILD] 데이터 저장 시간 변경 #12
  src/main/java/com/main/writeRoom/WriteRoomApplication.java
Labels: :penguin: infra

#130 [REFACTOR]
  src/main/java/com/main/writeRoom/WriteRoomApplication.java
  src/main/java/com/main/writeRoom/aws/s3/Uuid.java
  src/main/java/com/main/writeRoom/common/BaseEntity.java
  src/main/java/com/main/writeRoom/domain/Room.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/domain/mapping/RoomParticipation.java
Labels: :penguin: infra, ♻️ REFACTOR

#131 [REFACTOR] 노트북마크 인덱스 응답 추가 #123
  src/main/java/com/main/writeRoom/converter/BookmarkConverter.java
  src/main/java/com/main/writeRoom/web/dto/bookmark/BookmarkResponseDTO.java
Labels: ♻️ REFACTOR

#132 [FEATURE] 이모지 조회 API 추가 #120
  src/main/java/com/main/writeRoom/controller/BookmarkController.java
  src/main/java/com/main/writeRoom/controller/EmojiController.java
  src/main/java/com/main/writeRoom/converter/EmojiConverter.java
  src/main/java/com/main/writeRoom/domain/Bookmark/BookmarkMaterial.java
  src/main/java/com/main/writeRoom/domain/Emoji.java
  src/main/java/com/main/writeRoom/domain/Tag.java
  src/main/java/com/main/writeRoom/service/EmojiService/EmojiQueryService.java
  src/main/java/com/main/writeRoom/service/EmojiService/EmojiQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/emoji/EmojiResponseDTO.java
Labels: ✨ FEAT

#134 [FIX] 카카오 로그인 이메일 오류 수정 #104
  src/main/java/com/main/writeRoom/oauth/AuthController2.java
  src/main/java/com/main/writeRoom/oauth/OAuthLoginService.java
  src/main/java/com/main/writeRoom/oauth/infra/KakaoApiClient.java
  src/main/java/com/main/writeRoom/web/dto/user/UserResponseDTO.java
Labels: ⚒️ FIX

#136 [REFACTOR] 룸 응답 데이터에 룸 이미지 추가 #60
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/service/TagService/TagQueryService.java
  src/main/java/com/main/writeRoom/service/TagService/TagQueryServiceImpl.java
Labels: ♻️ REFACTOR

#137 [REFACTOR] 룸 응답 데이터에 룸 이미지 추가 #60
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
Labels: ♻️ REFACTOR

#138 [FEAT] 룸 정보 수정 #60
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/domain/Room.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandService.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomResponseDTO.java
Labels: ✨ FEAT

#139 [REFACTOR] 노트 수정 API 기능 수정 #133
  src/main/java/com/main/writeRoom/controller/EmojiController.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
Labels: ✨ FEAT

#141 [REFACTOR] 노트 수정 API 이미지 삭제 로직 변경 및 requestDTO 수정
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteRequestDTO.java
Labels: ♻️ REFACTOR

#142 [FIX] [FEAT] 룸 정보 수정 시 null 값 허용 및 룸 정보 조회 구현
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/domain/Room.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomResponseDTO.java
Labels: ✨ FEAT, ⚒️ FIX

#143 [FIX] 기본 회원가입 유저 JoinType.BASIC enum 추가 #81
  src/main/java/com/main/writeRoom/converter/UserConverter.java
  src/main/java/com/main/writeRoom/domain/User/JoinType.java
  src/main/java/com/main/writeRoom/web/dto/user/UserResponseDTO.java
Labels: ⚒️ FIX

#146 [FIX] @PostConstruct 추가
  src/main/java/com/main/writeRoom/WriteRoomApplication.java
  src/main/java/com/main/writeRoom/scheduler/ChallengeScheduler.java
Labels: ⚒️ FIX

#147 [FIX] 챌린지 스케줄러 테스트 #144
  src/main/java/com/main/writeRoom/scheduler/ChallengeScheduler.java
Labels: ⚒️ FIX

#148 [FIX] 챌린지 스케줄러 테스트 #144
  src/main/java/com/main/writeRoom/scheduler/ChallengeScheduler.java
Labels: ⚒️ FIX

#150 [FIX] 챌린지 스케줄러 수정 #144
  src/main/java/com/main/writeRoom/scheduler/ChallengeScheduler.java
Labels: ⚒️ FIX

#151 [REFACTOR] 노트 북마크 응답 데이터 추가 #123
  src/main/java/com/main/writeRoom/controller/NoteController.java
  src/main/java/com/main/writeRoom/converter/BookmarkConverter.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/bookmark/BookmarkResponseDTO.java
Labels: ♻️ REFACTOR

#153 [CI] 파일 업로드 제한 설정 위치 변경 #12
  .platform/conf.d/client_max_body_size.conf
  .platform/nginx.conf
  src/main/resources/application.yml
Labels: :penguin: infra

#154 [FEAT] 챌린지 타참여자 중복 생성 제한 및 리팩토링
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/ChallengeController.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineCommandServiceImpl.java
Labels: ✨ FEAT, ♻️ REFACTOR

#156 [FIX] 노트목록 리스트 조회시 북마크 여부 응답 추가
  .platform/nginx.conf
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/repository/BookmarkNoteRepository.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkService.java
  src/main/java/com/main/writeRoom/service/BookmarkService/BookmarkServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
Labels: ⚒️ FIX

#157 [FIX] 북마크노트 해제 시 noteId 요청으로 변경 #32
  src/main/java/com/main/writeRoom/controller/NoteController.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
Labels: ⚒️ FIX

#169 [FIX] 챌린지 달성 카운트 수정 #167
  src/main/java/com/main/writeRoom/controller/ChallengeController.java
  src/main/java/com/main/writeRoom/converter/ChallengeConverter.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryServiceImpl.java
Labels: ⚒️ FIX

#172 [REFACTOR] 인증메일 url 수정 #171
  src/main/java/com/main/writeRoom/service/MailService/EmailService.java
Labels: ♻️ REFACTOR

#174 [FIX] 챌린지 루틴 생성 날짜에 따른 노트 조회 수정 #170
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryServiceImpl.java
Labels: ⚒️ FIX
