Repository WRITE-ROOM/SERVER, pull requests merged in 2024-01, with the labels that each got.

#13 [FEAT] 나의 룸 목록에서 내가 참여중인 룸 리스트 조회
  src/main/java/com/main/writeRoom/WriteRoomApplication.java
  src/main/java/com/main/writeRoom/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/apiPayload/status/SuccessStatus.java
  src/main/java/com/main/writeRoom/common/BaseEntity.java
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/domain/Category.java
  src/main/java/com/main/writeRoom/domain/Room.java
  src/main/java/com/main/writeRoom/domain/Tag.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/domain/mapping/EmojiClick.java
  src/main/java/com/main/writeRoom/domain/mapping/NoteTag.java
  src/main/java/com/main/writeRoom/domain/mapping/RoomParticipation.java
  src/main/java/com/main/writeRoom/handler/UserHandler.java
  src/main/java/com/main/writeRoom/repository/RoomPaticipationRepository.java
  src/main/java/com/main/writeRoom/repository/RoomRepository.java
  src/main/java/com/main/writeRoom/repository/UserRepository.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandService.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
  src/main/java/com/main/writeRoom/validation/annotation/PageLessNull.java
  src/main/java/com/main/writeRoom/validation/validator/PageLessValidator.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/room/roomPaticipation/userRoomResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#15 [CI] elasticbeanstalk 무중단 배포를 위한 파일 생성 #12
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .github/workflows/gradle.yml
  .platform/conf.d/client_max_body_size.conf
  .platform/nginx.conf
  Dockerfile
  Procfile
  build.gradle
  docker-compose.yml
  src/main/java/com/main/writeRoom/controller/TestController.java
Labels: :penguin: infra

#16 [CI] 배포 브랜치 변경 #12
  .github/workflows/dev_deploy.yml
Labels: :penguin: infra

#20 [FEAT] 룸 관리
  build.gradle
  src/main/java/com/main/writeRoom/aws/s3/AmazonS3Manager.java
  src/main/java/com/main/writeRoom/aws/s3/Uuid.java
  src/main/java/com/main/writeRoom/config/AmazonConfig.java
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/domain/Note.java
  src/main/java/com/main/writeRoom/domain/Room.java
  src/main/java/com/main/writeRoom/domain/User/User.java
  src/main/java/com/main/writeRoom/domain/common/BaseEntity.java
  src/main/java/com/main/writeRoom/repository/UuidRepository.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandService.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/room/RoomResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/room/roomPaticipation/userRoomResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ FEAT

#24 [FEAT] 사용자 카테고리 생성 및 삭제
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/CategoryController.java
  src/main/java/com/main/writeRoom/converter/CategoryConverter.java
  src/main/java/com/main/writeRoom/domain/Category.java
  src/main/java/com/main/writeRoom/domain/Note.java
  src/main/java/com/main/writeRoom/handler/CategoryHandler.java
  src/main/java/com/main/writeRoom/handler/NoteHandler.java
  src/main/java/com/main/writeRoom/repository/CategoryRepository.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryCommandService.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryQueryService.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/category/CategoryRequestDTO.java
Labels: ✨ FEAT, ♻️ REFACTOR

#26 [REFACTOR] 사용자 카테고리 삭제 시 조건 수정
  src/main/java/com/main/writeRoom/controller/CategoryController.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryServiceImpl.java
Labels: ♻️ REFACTOR, ⚒️ FIX

#28 [REFACTOR] 서버 배포를 위한 카테고리 관련 구현 중단
  src/main/java/com/main/writeRoom/controller/CategoryController.java
  src/main/java/com/main/writeRoom/converter/CategoryConverter.java
  src/main/java/com/main/writeRoom/domain/Category.java
  src/main/java/com/main/writeRoom/repository/CategoryRepository.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryCommandService.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryCommandServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/category/CategoryResponseDTO.java
Labels: ✨ FEAT, ♻️ REFACTOR

#29 Feature/10 챌린지 루틴 생성, 조회, 포기 구현
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/ChallengeRestController.java
  src/main/java/com/main/writeRoom/converter/ChallengeConverter.java
  src/main/java/com/main/writeRoom/converter/ChallengeParticipationConverter.java
  src/main/java/com/main/writeRoom/domain/Challenge/ChallengeRoutine.java
  src/main/java/com/main/writeRoom/domain/mapping/ChallengeRoutineParticipation.java
  src/main/java/com/main/writeRoom/handler/ChallengeHandler.java
  src/main/java/com/main/writeRoom/repository/ChallengeRoutineParticipationRepository.java
  src/main/java/com/main/writeRoom/repository/ChallengeRoutineRepository.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/com/main/writeRoom/validation/annotation/DeadlineRange.java
  src/main/java/com/main/writeRoom/validation/annotation/IsStartDateToday.java
  src/main/java/com/main/writeRoom/validation/validator/ChallengeDeadlineValidator.java
  src/main/java/com/main/writeRoom/validation/validator/ChallengeStartDateValidator.java
  src/main/java/com/main/writeRoom/web/dto/challenge/ChallengeRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/challenge/ChallengeResponseDTO.java
Labels: ✨ FEAT

#31 [FEAT] 해당 룸에 대한 노트 리스트 조회 #9
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/domain/Note.java
  src/main/java/com/main/writeRoom/domain/mapping/NoteTag.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
  src/main/java/com/main/writeRoom/web/dto/tag/TagResponseDTO.java
Labels: ✨ FEAT

#33 [FEAT] 해당 룸 멤버들의 최근 수정일자 조회 #32
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/RoomConverter.java
  src/main/java/com/main/writeRoom/domain/Note.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandService.java
  src/main/java/com/main/writeRoom/service/RoomService/RoomCommandServiceimpl.java
  src/main/java/com/main/writeRoom/web/dto/room/roomPaticipation/userRoomResponseDTO.java
Labels: ✨ FEAT

#35 [FEAT] 북마크 노트 API #34
  src/main/java/com/main/writeRoom/controller/NoteController.java
  src/main/java/com/main/writeRoom/converter/NoteConverter.java
  src/main/java/com/main/writeRoom/repository/BookmarkNoteRepository.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/note/NoteResponseDTO.java
Labels: ✨ FEAT

#36 Feature/27 [FEAT] 챌린지 목표량 생성, 조회, 포기 구현
  src/main/java/com/main/writeRoom/apiPayload/status/ErrorStatus.java
  src/main/java/com/main/writeRoom/controller/ChallengeRestController.java
  src/main/java/com/main/writeRoom/converter/ChallengeConverter.java
  src/main/java/com/main/writeRoom/converter/ChallengeParticipationConverter.java
  src/main/java/com/main/writeRoom/domain/mapping/ChallengeGoalsParticipation.java
  src/main/java/com/main/writeRoom/repository/ChallengeGoalsParticipationRepository.java
  src/main/java/com/main/writeRoom/repository/ChallengeGoalsRepository.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeGoalsQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineCommandService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryService.java
  src/main/java/com/main/writeRoom/service/ChallengeService/ChallengeRoutineQueryServiceImpl.java
  src/main/java/com/main/writeRoom/validation/annotation/IsStartDateTodayNull.java
  src/main/java/com/main/writeRoom/validation/validator/ChallengeStartDateNullValidator.java
  src/main/java/com/main/writeRoom/validation/validator/ChallengeStartDateValidator.java
  src/main/java/com/main/writeRoom/web/dto/challenge/ChallengeRequestDTO.java
  src/main/java/com/main/writeRoom/web/dto/challenge/ChallengeResponseDTO.java
Labels: ✨ FEAT

#37 [FEAT] 카테고리 관리 API
  src/main/java/com/main/writeRoom/controller/CategoryController.java
  src/main/java/com/main/writeRoom/controller/RoomController.java
  src/main/java/com/main/writeRoom/converter/CategoryConverter.java
  src/main/java/com/main/writeRoom/repository/NoteRepository.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryCommandService.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryCommandServiceImpl.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryQueryService.java
  src/main/java/com/main/writeRoom/service/CategoryService/CategoryQueryServiceImpl.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryService.java
  src/main/java/com/main/writeRoom/service/NoteService/NoteQueryServiceImpl.java
  src/main/java/com/main/writeRoom/web/dto/category/CategoryResponseDTO.java
Labels: ✨ FEAT
